QUERY = "QUERY"
REPLICATION = "REPLICATION"

HEARTBEAT = "HEARTBEAT"
HEARTBEAT_ACK = "HEARTBEAT_ACK"

ELECTION = "ELECTION"
ELECTION_OK = "ELECTION_OK"
COORDINATOR_ANNOUNCEMENT = "COORDINATOR_ANNOUNCEMENT"

TRANSACTION_PREPARE = "TRANSACTION_PREPARE"
TRANSACTION_VOTE_YES = "TRANSACTION_VOTE_YES"
TRANSACTION_VOTE_NO = "TRANSACTION_VOTE_NO"
TRANSACTION_COMMIT = "TRANSACTION_COMMIT"
TRANSACTION_ABORT = "TRANSACTION_ABORT"
TRANSACTION_ROLLBACK = "TRANSACTION_ROLLBACK"

QUERY_RESPONSE = "QUERY_RESPONSE"
REPLICATION_ACK = "REPLICATION_ACK"
REPLICATION_NACK = "REPLICATION_NACK"
ERROR = "ERROR"
ACK = "ACK"

NODE_STATUS = "NODE_STATUS"
HEALTH_CHECK = "HEALTH_CHECK"
HEALTH_RESPONSE = "HEALTH_RESPONSE"

LOCK_REQUEST = "LOCK_REQUEST"
LOCK_GRANTED = "LOCK_GRANTED"
LOCK_DENIED = "LOCK_DENIED"
LOCK_RELEASE = "LOCK_RELEASE"


def is_transaction_message(message_type: str) -> bool:

    transaction_types = [
        TRANSACTION_PREPARE,
        TRANSACTION_VOTE_YES,
        TRANSACTION_VOTE_NO,
        TRANSACTION_COMMIT,
        TRANSACTION_ABORT,
        TRANSACTION_ROLLBACK
    ]
    return message_type in transaction_types


def is_election_message(message_type: str) -> bool:

    election_types = [ELECTION, ELECTION_OK, COORDINATOR_ANNOUNCEMENT]
    return message_type in election_types


def is_heartbeat_message(message_type: str) -> bool:

    return message_type in [HEARTBEAT, HEARTBEAT_ACK]
